### ISSUE TITLE
 It works on PC, but not on Android. 

### ISSUE THREAD

**Issue by BoboHoo** [PikaTer/quora-unblur-images#1]
It cannot be expanded or unblur automatically, but manually clicking the button is effective.
Could you please fix it? Thanks.

**Comment by BoboHoo** [comment]
It still doesn't work. 
On mobile phones, posts have two buttons: "Read more" and "Continue reading". The manual expansion function can only skip the "Read more" button.
After updating the latest code, the PC web version will automatically expand the comment area, which is not a good experience. Alternatively, add buttons to automatically/manually expand the comment area.

**Comment by PikaTer** [comment]
> After updating the latest code, the PC web version will automatically expand the comment area

Hi, thank you for taking interest in making this a better script. I managed to identify and fix the post expansion in mobile web version but seems unable to identify and reproduce the comment area expand issue. Could you please provide more information on this?

- URL you are testing against
- Browser & Version you are using
- OS you are on

Thanks!

**Comment by BoboHoo** [comment]
Hi, thank you for your reply. Maybe I didn't express it clearly and you misunderstood. In fact, I use both the computer web version and the mobile web version, so I will describe it again in these two aspects.

On the computer, the 0.6.1 version of the script works great. But after updating to 0.6.2, the comment section expand automatically. I'd suggest removing this feature or adding buttons to expand / collapse the comment section automatically or manually.

On mobile, if I'm on the home page or viewing someone's  profile page, some features don't work:
1. ❌ Unblur images automatically
2.  ✔Unblur / Re-blur images manually
3.  ❌Expand posts automatically
4.  ❌ Expand posts manually ( The post or answers will successively pop up two buttons: "Read more" and "Continue reading". The manual expansion features can only skip the "Read more" button.)

Here is the test page and my device information:

https://www.quora.com/profile/PRASHANT-M-OSWAL

Computer version:
- Edge 131.0.2903.70
- Win10
- Tampermonkey 5.3.2

Mobile version:
- Edge 130.0.2849.68
- Android12
- Tampermonkey 5.3.2

**Comment by PikaTer** [comment]
Thanks for your input. However, after inspection, it seems that there is not much I can do on the comment expansion issue. The comment expansion seems to be a default behavior of Quora on certain type of pages (e.g. someone's profile page), tested when manually clicking on the post itself / clicking on read more button.

I can automatically collapse all comments section after post expansion but that might add complexity and might be an unwanted behavior for others.

However, I will add the comment expansion and collapse feature in the roadmap as a feature to be anticipated in the future 😉

**Comment by BoboHoo** [comment]
I tested the issue of the comment section expanding again, and it turns out it's indeed Quora's default behavior on some users' profiles. I made a mistake before.

And I also found that only the comment section for posts expands, not for answers.

The latest code is running smoothly on my phone. Thanks a lot!
